version: '1.0'

services:
  backend:
    image: mcr.microsoft.com/dotnet/core/aspnet:5.0
    ports:
      - "5000:80"

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=YourPassword123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"