<<<<<<< HEAD
name: .NET Build and Test
=======
name: .NET Workflow
>>>>>>> develop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
<<<<<<< HEAD
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
=======
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    - run: dotnet restore
    - run: dotnet build
    - run: dotnet test
>>>>>>> develop
